name: pdf
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  syncfusion_flutter_pdf: ^20.4.54
  syncfusion_flutter_pdfviewer: ^20.4.54
  syncfusion_flutter_signaturepad: ^20.4.54
  file_picker: ^8.1.2
  path_provider: ^2.0.11
  flutter_colorpicker: ^1.0.3
  google_fonts: ^4.0.4
  file_saver: ^0.2.6
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true